//! Byte-by-byte generation with a persistent recurrent state, shared by
//! sample and chat (port of src/generate.h). It runs exactly the training
//! forward with one stream and one position, so a generated byte sees the
//! same computation a trained byte did.
const std = @import("std");
const gpu = @import("gpu.zig");
const cfgmod = @import("config.zig");
const checkpoint = @import("checkpoint.zig");
const session = @import("session.zig");
const stdrand = @import("../stdrand.zig");

extern "c" fn exp(x: f64) f64;

pub const Generator = struct {
    file_cfg: cfgmod.Cfg,
    s: session.Session,
    rng: stdrand.Mt19937,
    logits: [256]f32 = @splat(0),
    /// Sigmoid of the stop head for the last fed byte.
    stop_prob: f32 = 0,
    /// Whether `logits` holds the prediction after the last fed byte.
    ready: bool = false,
    /// Bytes fed since the last reset.
    fed: i64 = 0,

    pub fn open(gpa: std.mem.Allocator, io: std.Io, path: []const u8, seed: u32, ptx: [:0]const u8) !Generator {
        const file_cfg = try checkpoint.readConfig(gpa, io, path);
        var cfg = file_cfg;
        cfg.batch = 1; // one step at a time; both are runtime keys
        cfg.seqlen = 1;
        try cfgmod.validate(cfg);
        var g = Generator{
            .file_cfg = file_cfg,
            .s = try session.Session.init(gpa, io, cfg, ptx),
            .rng = stdrand.Mt19937.init(seed),
        };
        g.s.attach();
        try checkpoint.loadWeights(gpa, io, path, &g.s.m, file_cfg);
        return g;
    }
    pub fn close(g: *Generator) void {
        g.s.deinit();
    }
    /// An untrained stop head (stop=0) produces arbitrary logits and is ignored.
    pub fn stopTrained(g: *const Generator) bool {
        return g.file_cfg.stop > 0;
    }

    pub fn feed(g: *Generator, byte: u8) !void {
        const ids = [_]i32{byte};
        const nxt = [_]i32{-1};
        const end = [_]i32{0};
        _ = try g.s.forward(&ids, &nxt, &end);
        var raw: [256]u16 = undefined;
        var stop: u16 = 0;
        try gpu.download(std.mem.sliceAsBytes(raw[0..]), g.s.m.logits);
        try gpu.download(std.mem.asBytes(&stop), g.s.m.stoplog);
        for (raw, 0..) |bits, i| g.logits[i] = @bitCast(@as(u32, bits) << 16);
        const z: f32 = @bitCast(@as(u32, stop) << 16);
        g.stop_prob = 1.0 / (1.0 + @exp(-z));
        g.ready = true;
        g.fed += 1;
    }
    pub fn feedText(g: *Generator, text: []const u8) !void {
        for (text) |c| try g.feed(c);
    }
    pub fn reset(g: *Generator) !void {
        try g.s.resetState();
        g.ready = false;
        g.fed = 0;
    }

    /// The next byte from the prediction after the last fed byte; the argmax
    /// when temp <= 0, otherwise a draw from the softmax at that temperature.
    pub fn sample(g: *Generator, temp: f32) u8 {
        std.debug.assert(g.ready);
        var best: usize = 0;
        for (g.logits, 0..) |v, i| if (v > g.logits[best]) {
            best = i;
        };
        if (temp <= 0) return @intCast(best);
        const mx = g.logits[best];
        var p: [256]f64 = undefined;
        var sum: f64 = 0;
        for (g.logits, 0..) |v, i| {
            const d: f32 = (v - mx) / temp; // float arithmetic, then a double exp, as in C++
            p[i] = exp(d);
            sum += p[i];
        }
        var r = g.rng.canonical() * sum;
        for (p, 0..) |pi, i| {
            r -= pi;
            if (r <= 0) return @intCast(i);
        }
        return 255;
    }
};
